name: CI

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'
  workflow_call:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs: test
    uses: ./.github/workflows/release.yml
